language: node_js

node_js:
  - '6'

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: RJRFgw2Aj/rSacCjOJEX5pMjH4pXz9bZYbs5m+qR6lEZk5mQqS2T3tghuCyOZR/KEkLxZMIWnzl1zYPZbOaRCJcsLThXmBZcac12aN1RtyGCgpTCBI18WwQoEWTGbBN3VbEbuHZ8WrQ2azyWksv3Pu6uoGLkdmTJD6MsXW332o4A+IT/0Zb66IRPncd4PWExxZYnUGGs9ZNA7A+w/IM+6WZtoVqk3W7sTOiH8RuqeK2NADZGzdXBmCsi4IYxMPhyN8KdiHYkhtJUqCeX5wyrpencZe8VUE1KxTcaK/xTmNDZkX1fkt7CfFqLojpJAL3AqRiajJ8B3k5YKbegR0nn6GS/WgmmThC/SYthUcUFl0bhqq6B8q8xn/LSB5W+RtiydIxE9Wm3ltfKhQT+sD0KmWD6ggTTKUwlsNxUxj/aamYKqopQaWOpjvCNBpqFQ6ojW7jkFqxpHtVpv5cycyFiDad+9Bw+9TsIyHz5V9z9l8dPPfsqA44+4aCBKPpTVxc/PWY70IHJDsQJKoPVQwVGNwwF2/Z7nbpJIg+GtG1GWCkYibHXjstZm2Cj9kUnHev8NP02kefoLuR8OvKacl7NE/1ZSRHDvpw7NvvUKbganvhFmCrEeFC1Yr2gI1AcYvmKU8Hlvxi9sF8++2UrIFMtq4d+uqK6GzzbH1ETzcLHB2k=
  local_dir: build
  target_branch: 'gh-pages'
  on:
    repo: catdad/chord-explorer
    branch: '*'
    tags: true
