language: node_js

node_js:
  - '6'

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: YLiRCrhcMHittVL95b7zPX8ojTRjch+S3fLKBhfcuLFZAv/GRHJayMsZ6G4Yix/rde8I+vQiwzrn8vD466XYI/wuacqLanKH3wU2idjTyrSKyTAFOeulLe2yb7s6CgDITJspKJ8brVijWwqrM/A7ik2NSbnuTg+KBtx7b6ToTBwFNdwWI0zxgESoDNi0T3vX9TqT+x4c+SOTSgUnzFm+1S4B4ZSH+xeDiNqN8ryvxdndanb1X0Imf17K8n6RAbBGSBv7cUnLBt/RKKEkllECSbrvZPVAgYLVDUtSFYz2nP74YSCK6jS2mvuhqCW4zO3zW1UmA7RolWVwcSO94p7lCjkw6yKXLHq3wgoxbpnQxBn9xj8fZjJ+btSoO9wStlk46p0HOhVzHe5/8osookcru7KV5UB9hzBgLwZblUwbjKSEhJ46yyuZl51bFHGm6RiGOE8EFoDeAvOhOkwecSkfjH+y7nJouOg48w/zHrDB2xY+IfArYv2rt/6UCuzE2sZ1CGgHQ2c39V6Fc40a18vabL+a2WqfjaanCRYSjzYd1KAmUyMonlRGGhps/lMUMXjdg6JQsQCuHHhzlUV5AvRxiCWuN1XwGAzhRd6oe/8/BrZKry0M/WaZui1ccq68CGr2VvKZT9seppAlIuncsdCa0eRkDFvbUciu6tXJ7Gnodec=
  local_dir: dist
  target_branch: 'gh-pages'
  on:
    repo: catdad/chord-explorer
    branch: '*'
    tags: true
